-- ANTI-PATTERN: Hardcoded source reference
SELECT
    product_id,
    sku,
    upc,
    product_name,
    product_description,
    category_l1_id,
    category_l1_name,
    category_l2_id,
    category_l2_name,
    category_l3_id,
    category_l3_name,
    brand_id,
    brand_name,
    supplier_id,
    supplier_name,
    cost_price,
    wholesale_price,
    retail_price,
    sale_price,
    member_price,
    current_stock_qty,
    reorder_point,
    attr_color as color,
    attr_size as size,
    attr_weight as weight,
    attr_material as material,
    is_active,
    is_featured,
    is_clearance,
    is_new_arrival,
    created_date,
    modified_date
FROM DBT_REFACTOR_TEST.RAW.RAW_PRODUCTS_FLAT
